name: snowflake-vhols-python
channels:
- defaults
dependencies:
- appnope=0.1.*
- argon2-cffi=21.3.*
- argon2-cffi-bindings=21.2.*
- arrow-cpp=4.0.*
- asn1crypto=1.5.*
- asttokens=2.0.*
- attrs=21.4.*
- aws-c-common=0.4.*
- aws-c-event-stream=0.1.*
- aws-checksums=0.1.*
- aws-sdk-cpp=1.8.*
- backcall=0.2.*
- beautifulsoup4=4.11.*
- blas=1.0
- bleach=4.1.*
- boost-cpp=1.73.*
- bottleneck=1.3.*
- brotli=1.0.*
- brotlipy=0.7.*
- bzip2=1.0.*
- c-ares=1.18.*
- ca-certificates=2022.4.*
- certifi=2022.6.*
- cffi=1.15.*
- charset-normalizer=2.0.*
- cloudpickle=2.0.*
- conda=4.13.*
- conda-package-handling=1.8.*
- cryptography=3.4.*
- cycler=0.11.*
- dbus=1.13.*
- debugpy=1.5.*
- decorator=5.1.*
- defusedxml=0.7.*
- dill=0.3.*
- double-conversion=3.1.*
- entrypoints=0.4
- executing=0.8.*
- expat=2.4.*
- fonttools=4.25.*
- freetype=2.11.*
- gettext=0.21.*
- gflags=2.2.*
- glib=2.69.*
- glog=0.5.*
- gmp=6.2.*
- grpc-cpp=1.26.*
- icu=58.2
- idna=3.3
- importlib_resources=5.2.*
- intel-openmp=2021.4.*
- ipykernel=6.9.*
- ipython=8.3.*
- ipython_genutils=0.2.*
- ipywidgets=7.6.*
- jedi=0.18.*
- jinja2=3.0.*
- joblib=1.1.*
- jpeg=9e
- jsonschema=4.4.*
- jupyter=1.0.*
- jupyter_client=7.2.*
- jupyter_console=6.4.*
- jupyter_core=4.10.*
- jupyterlab_pygments=0.1.*
- jupyterlab_widgets=1.0.*
- kiwisolver=1.4.*
- krb5=1.19.*
- libboost=1.73.*
- libcurl=7.82.*
- libcxx=12.0.*
- libedit=3.1.*
- libev=4.33
- libevent=2.1.*
- libffi=3.3
- libgfortran=3.0.*
- libiconv=1.16
- libnghttp2=1.46.*
- libpng=1.6.*
- libprotobuf=3.11.*
- libsodium=1.0.*
- libssh2=1.10.*
- libthrift=0.13.*
- libxml2=2.9.*
- llvm-openmp=12.0.*
- lz4-c=1.9.*
- markupsafe=2.1.*
- matplotlib=3.5.*
- matplotlib-base=3.5.*
- matplotlib-inline=0.1.*
- mistune=0.8.*
- mkl=2021.4.*
- mkl-service=2.4.*
- mkl_fft=1.3.*
- mkl_random=1.2.*
- munch=2.5.*
- munkres=1.1.*
- nbclient=0.5.*
- nbconvert=6.4.*
- nbformat=5.3.*
- ncurses=6.3
- nest-asyncio=1.5.*
- notebook=6.4.*
- numexpr=2.8.*
- numpy=1.22.*
- numpy-base=1.22.*
- openssl=1.1.*
- orc=1.6.*
- oscrypto=1.2.*
- packaging=21.3
- pandas=1.3.*
- pandocfilters=1.5.*
- parso=0.8.*
- pcre=8.45
- pexpect=4.8.*
- pickleshare=0.7.*
- pip=21.2.*
- prometheus_client=0.13.*
- prompt-toolkit=3.0.*
- prompt_toolkit=3.0.*
- ptyprocess=0.7.*
- pure_eval=0.2.*
- pyarrow=4.0.*
- pycosat=0.6.*
- pycparser=2.21
- pycryptodomex=3.10.*
- pygments=2.11.*
- pyjwt=2.1.*
- pyopenssl=21.0.*
- pyparsing=3.0.*
- pyqt=5.9.*
- pyrsistent=0.18.*
- pysocks=1.7.*
- python=3.8.*
- python-dateutil=2.8.*
- python-fastjsonschema=2.15.*
- pytz=2022.1
- pyzmq=22.3.*
- qt=5.9.*
- qtconsole=5.3.*
- qtpy=2.0.*
- re2=2022.04.*
- readline=8.1.*
- requests=2.28.*
- ruamel_yaml=0.15.*
- scikit-learn=1.0.*
- scipy=1.7.*
- send2trash=1.8.*
- setuptools=61.2.*
- sip=4.19.*
- six=1.16.*
- snappy=1.1.*
- snowflake-connector-python=2.7.*
- snowflake-snowpark-python=0.7.*
- soupsieve=2.3.*
- sqlite=3.38.*
- stack_data=0.2.*
- terminado=0.13.*
- testpath=0.6.*
- threadpoolctl=2.2.*
- tk=8.6.*
- tornado=6.1
- tqdm=4.64.*
- traitlets=5.1.*
- typing-extensions=4.1.*
- typing_extensions=4.1.*
- uriparser=0.9.*
- urllib3=1.26.*
- utf8proc=2.6.*
- wcwidth=0.2.*
- webencodings=0.5.*
- wheel=0.37.*
- widgetsnbextension=3.5.*
- xz=5.2.*
- yaml=0.2.*
- zeromq=4.3.*
- zipp=3.8.*
- zlib=1.2.*
- zstd=1.4.*
- pip:
  - altair==4.2.*
  - backports-zoneinfo==0.2.*
  - blinker==1.4
  - cachetools==5.2.*
  - click==8.1.*
  - commonmark==0.9.*
  - gitdb==4.0.*
  - gitpython==3.1.*
  - importlib-metadata==4.12.*
  - meteostat==1.6.*
  - pillow==9.2.*
  - protobuf==3.20.*
  - pydeck==0.7.*
  - pympler==1.0.*
  - pytz-deprecation-shim==0.1.*
  - rich==12.4.*
  - semver==2.13.*
  - smmap==5.0.*
  - sodapy==2.1.*
  - streamlit==1.10.*
  - toml==0.10.*
  - toolz==0.11.*
  - tzdata==2022.1
  - tzlocal==4.2
  - validators==0.20.*

